installation:
  package_set: desktop-full
  parallel_jobs: 4
  retry_attempts: 3
  ros_distro: kilted
  timeout_seconds: 300
  uninstall_existing: true
logging:
  console: true
  file: /tmp/ros2_installation.log
  level: INFO
performance:
  compression: true
  download_cache: true
  parallel_downloads: true
security:
  audit_logging: true
  check_checksums: true
  secure_permissions: true
  verify_signatures: true
system:
  backup_configs: true
  install_dependencies: true
  update_system: true
  verify_compatibility: true
validation:
  min_disk_space_gb: 4
  min_memory_gb: 2
  required_ubuntu_version: '24.04'
  supported_architectures:
  - amd64
  - arm64
  - aarch64
  - x86_64
