# ROS2 Kilted Kaiju CLI Professional Installer Configuration
# ===========================================================

# Installation Configuration
installation:
  ros_distro: "kilted"
  package_set: "desktop-full"  # minimal, base, desktop, desktop-full
  uninstall_existing: true
  parallel_jobs: 1
  retry_attempts: 3
  timeout_seconds: 1200

# System Configuration
system:
  update_system: true
  install_dependencies: true
  backup_configs: true
  verify_compatibility: true

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "/tmp/ros2_installation.log"
  console: true

# Validation Rules
validation:
  min_disk_space_gb: 4
  min_memory_gb: 2
  required_ubuntu_version: "24.04"
  supported_architectures: ["amd64", "arm64", "aarch64"]

# Performance Tuning
performance:
  parallel_downloads: true
  download_cache: true
  compression: true

# Security Configuration
security:
  verify_signatures: true
  check_checksums: true
  secure_permissions: true
  audit_logging: true
